version: '2'
services:
  jenkins:
    build: ../../docker-images/sea-jenkins
    image: sea/jenkins
    restart: always
    dns: "8.8.8.8"
    ports:
     - "50000:50000"
     - "18080:8080"
    volumes:
#     - jenkins-data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
  sonar:
    image: sonarqube
    restart: always
    dns: "8.8.8.8"
    ports:
      - "9000:9000"
      - "9092:9092" 