version: '2'
services:
  clock-service:
    image: sea/service_clock
    restart: always
    dns: "8.8.8.8"
    ports:
     - "28001:8080"
  beers-service:
    image: sea/service_beers
    restart: always
    dns: "8.8.8.8"
    ports:
     - "28002:8080"
